name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

      redis:
        image: redis:latest
        ports:
          - 6379:6379

    env:
      MONGODB_URI: mongodb://localhost:27017/testdb
      
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install
          npm install amqp-connection-manager @nestjs/platform-socket.io
          npm install kerberos
          npm install @mongodb-js/zstd
          npm install @aws-sdk/credential-providers
          npm install gcp-metadata

      - name: Install additional dependencies
        run: npm install snappy socks aws4 mongodb-client-encryption @nestjs/websockets @nestjs/microservices


      - name: Install webpack-cli
        run: npm install -D webpack-cli
      
      - name: Run Webpack
        run: npx webpack --config webpack.config.js
      
      - name: Run tests
        run: npm test
